spring:
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: Bootstrap Spring Boot
  thymeleaf:
    cache: 'false'
    enabled: 'true'
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: 'true'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: DEBUG
server:
  servlet:
    context-path: /demo
  port: '8080'
